# Generated by Django 5.2.1 on 2025-10-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriasproductoselaborados_es_intermediario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadosordencompra',
            old_name='nombre_estado_oc',
            new_name='nombre_estado',
        ),
        migrations.RenameField(
            model_name='estadosordenventa',
            old_name='nombre_estado_ov',
            new_name='nombre_estado',
        ),
    ]
