# Generated by Django 5.2.1 on 2025-11-18 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nombre_estado_oc_estadosordencompra_nombre_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionesUnidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_conversion', models.DecimalField(decimal_places=6, help_text='Factor de conversión: 1 unidad_origen = X unidad_destino', max_digits=15)),
                ('unidad_destino', models.ForeignKey(help_text='Unidad a la cual se convierte', on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_destino', to='core.unidadesdemedida')),
                ('unidad_origen', models.ForeignKey(help_text='Unidad desde la cual se convierte', on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='core.unidadesdemedida')),
            ],
            options={
                'verbose_name': 'Conversión de Unidad',
                'verbose_name_plural': 'Conversiones de Unidades',
                'unique_together': {('unidad_origen', 'unidad_destino')},
            },
        ),
    ]
