# Generated by Django 5.2.1 on 2025-11-18 03:07

from django.db import migrations
from decimal import Decimal


def seed_unit_conversions(apps, schema_editor):
    """
    Seed common unit conversions for peso and volumen.
    This allows flexible purchase units across different providers.
    """
    UnidadesDeMedida = apps.get_model('core', 'UnidadesDeMedida')
    ConversionesUnidades = apps.get_model('core', 'ConversionesUnidades')
    
    # Get or create common units - only if they exist
    # We'll create conversions for units that already exist in the system
    
    conversions_to_create = []
    
    # Try to get common weight units
    try:
        kg = UnidadesDeMedida.objects.get(abreviatura='kg', tipo_medida='peso')
        g = UnidadesDeMedida.objects.get(abreviatura='g', tipo_medida='peso')
        
        # kg <-> g conversions
        conversions_to_create.extend([
            ConversionesUnidades(unidad_origen=kg, unidad_destino=g, factor_conversion=Decimal('1000.000000')),
            ConversionesUnidades(unidad_origen=g, unidad_destino=kg, factor_conversion=Decimal('0.001000')),
        ])
    except UnidadesDeMedida.DoesNotExist:
        pass
    
    # Try to get lb (pounds) if it exists
    try:
        lb = UnidadesDeMedida.objects.get(abreviatura='lb', tipo_medida='peso')
        g = UnidadesDeMedida.objects.get(abreviatura='g', tipo_medida='peso')
        
        conversions_to_create.extend([
            ConversionesUnidades(unidad_origen=lb, unidad_destino=g, factor_conversion=Decimal('453.592000')),
            ConversionesUnidades(unidad_origen=g, unidad_destino=lb, factor_conversion=Decimal('0.002205')),
        ])
    except UnidadesDeMedida.DoesNotExist:
        pass
    
    # Try to get oz (ounces) if it exists
    try:
        oz = UnidadesDeMedida.objects.get(abreviatura='oz', tipo_medida='peso')
        g = UnidadesDeMedida.objects.get(abreviatura='g', tipo_medida='peso')
        
        conversions_to_create.extend([
            ConversionesUnidades(unidad_origen=oz, unidad_destino=g, factor_conversion=Decimal('28.349500')),
            ConversionesUnidades(unidad_origen=g, unidad_destino=oz, factor_conversion=Decimal('0.035274')),
        ])
    except UnidadesDeMedida.DoesNotExist:
        pass
    
    # Try to get common volume units
    try:
        l = UnidadesDeMedida.objects.get(abreviatura='L', tipo_medida='volumen')
        ml = UnidadesDeMedida.objects.get(abreviatura='ml', tipo_medida='volumen')
        
        conversions_to_create.extend([
            ConversionesUnidades(unidad_origen=l, unidad_destino=ml, factor_conversion=Decimal('1000.000000')),
            ConversionesUnidades(unidad_origen=ml, unidad_destino=l, factor_conversion=Decimal('0.001000')),
        ])
    except UnidadesDeMedida.DoesNotExist:
        pass
    
    # Try to get gallon if it exists
    try:
        gal = UnidadesDeMedida.objects.get(abreviatura='gal', tipo_medida='volumen')
        ml = UnidadesDeMedida.objects.get(abreviatura='ml', tipo_medida='volumen')
        
        conversions_to_create.extend([
            ConversionesUnidades(unidad_origen=gal, unidad_destino=ml, factor_conversion=Decimal('3785.410000')),
            ConversionesUnidades(unidad_origen=ml, unidad_destino=gal, factor_conversion=Decimal('0.000264')),
        ])
    except UnidadesDeMedida.DoesNotExist:
        pass
    
    # Bulk create all conversions
    if conversions_to_create:
        ConversionesUnidades.objects.bulk_create(conversions_to_create, ignore_conflicts=True)


def reverse_seed(apps, schema_editor):
    """Remove seeded conversions"""
    ConversionesUnidades = apps.get_model('core', 'ConversionesUnidades')
    ConversionesUnidades.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversionesunidades'),
    ]

    operations = [
        migrations.RunPython(seed_unit_conversions, reverse_seed),
    ]
