# Generated by Django 5.2.1 on 2025-11-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_unit_conversions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('Bajo stock', 'Bajo stock'), ('Sin stock', 'Sin stock'), ('Expiración', 'Expiración'), ('Entrega cercana', 'Entrega cercana')], max_length=50)),
                ('tipo_producto', models.CharField(choices=[('Materia prima', 'Materia prima'), ('Productos elaborados', 'Productos elaborados'), ('Productos intermedios', 'Productos intermedios'), ('Productos de reventa', 'Productos de reventa')], max_length=50)),
                ('producto_id', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
        ),
    ]
