# Generated by Django 5.2.1 on 2025-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='tipo_producto',
            field=models.CharField(choices=[('Materia prima', 'Materia prima'), ('Productos elaborados', 'Productos elaborados'), ('Productos intermedios', 'Productos intermedios'), ('Productos de reventa', 'Productos de reventa'), ('Ordenes de venta', 'Ordenes de venta')], max_length=50),
        ),
    ]
