# Generated by Django 5.2.1 on 2025-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notificaciones_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='tipo_producto',
            field=models.CharField(choices=[('Materia prima', 'Materia prima'), ('Productos finales', 'Productos finales'), ('Productos intermedios', 'Productos intermedios'), ('Productos de reventa', 'Productos de reventa'), ('Ordenes de venta', 'Ordenes de venta')], max_length=50),
        ),
    ]
