# Generated by Django 5.2.1 on 2026-01-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notificaciones_tipo_producto'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificaciones',
            constraint=models.UniqueConstraint(condition=models.Q(('leida', False)), fields=('tipo_notificacion', 'tipo_producto', 'producto_id', 'prioridad'), name='unique_unread_notification'),
        ),
    ]
