# Generated by Django 5.2.1 on 2025-06-23 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProduccionCosumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LogTransformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto_entrada_efectiva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_producto_salida_total_generado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario_entrada_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total_entrada_calculado_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario_salida_calculado_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_produccion', models.DateField()),
                ('costo_total_componentes_usd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefinicionTransformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_salida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=False)),
                ('producto_elaborado_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformaciones_como_entrada', to='inventario.productoselaborados')),
                ('producto_elaborado_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformaciones_como_salida', to='inventario.productoselaborados')),
                ('unidad_medida_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformaciones_unidad_entrada', to='core.unidadesdemedida')),
                ('unidad_medida_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformaciones_unidad_salida', to='core.unidadesdemedida')),
            ],
        ),
    ]
