# Generated by Django 5.2.1 on 2025-08-05 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0002_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='definiciontransformacion',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='lote_materia_prima_consumida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotesmateriasprimas'),
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='lote_producto_intermedio_consumido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotesproductoselaborados'),
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='materia_prima_consumida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas'),
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='producto_intermedio_consumido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productoselaborados'),
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='logtransformacion',
            name='definicion_transformacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.definiciontransformacion'),
        ),
        migrations.AddField(
            model_name='logtransformacion',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produccion',
            name='producto_elaborado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productoselaborados'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.produccion'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='componente_materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='componente_producto_intermedio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_como_componente', to='inventario.productoselaborados'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='producto_elaborado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_como_producto_final', to='inventario.productoselaborados'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='receta_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.recetasdetalles'),
        ),
        migrations.AddConstraint(
            model_name='detalleproduccioncosumos',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('materia_prima_consumida__isnull', False), ('lote_materia_prima_consumida__isnull', False), ('producto_intermedio_consumido__isnull', True), ('lote_producto_intermedio_consumido__isnull', True)), models.Q(('materia_prima_consumida__isnull', True), ('lote_materia_prima_consumida__isnull', True), ('producto_intermedio_consumido__isnull', False), ('lote_producto_intermedio_consumido__isnull', False)), _connector='OR'), name='materia_prima_or_producto_intermedio_and_lote_required'),
        ),
        migrations.AddConstraint(
            model_name='recetas',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('componente_materia_prima__isnull', False), ('componente_producto_intermedio__isnull', True)), models.Q(('componente_materia_prima__isnull', True), ('componente_producto_intermedio__isnull', False)), _connector='OR'), name='receta_un_solo_tipo_componente'),
        ),
    ]
