# Generated by Django 5.2.1 on 2025-08-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_initial'),
        ('produccion', '0003_force_create_recetas_detalles'),
    ]

    operations = [
    ]
