# Generated by Django 5.2.1 on 2025-08-05 18:29

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('produccion', '0004_merge_0002_initial_0003_force_create_recetas_detalles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recetas',
            name='receta_un_solo_tipo_componente',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='componente_materia_prima',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='componente_producto_intermedio',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='receta_detalle',
        ),
        migrations.RemoveField(
            model_name='recetasdetalles',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='recetasdetalles',
            name='nombre',
        ),
        migrations.AddField(
            model_name='recetas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recetas',
            name='nombre',
            field=models.CharField(default='Receta', max_length=255),
        ),
        migrations.AddField(
            model_name='recetasdetalles',
            name='componente_materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas'),
        ),
        migrations.AddField(
            model_name='recetasdetalles',
            name='componente_producto_intermedio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_como_componente', to='inventario.productoselaborados'),
        ),
        migrations.AddField(
            model_name='recetasdetalles',
            name='receta',
            field=models.ForeignKey(
                null=True, blank=True,     # ← Allows NULL values
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='componentes', 
                to='produccion.recetas'
            ),
        ),
        migrations.AddConstraint(
            model_name='recetasdetalles',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('componente_materia_prima__isnull', False), ('componente_producto_intermedio__isnull', True)), models.Q(('componente_materia_prima__isnull', True), ('componente_producto_intermedio__isnull', False)), _connector='OR'), name='receta_un_solo_tipo_componente'),
        ),
    ]
