# Generated by Django 5.2.1 on 2025-08-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_remove_recetas_receta_un_solo_tipo_componente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
