# Generated by Django 5.2.1 on 2025-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_alter_recetas_fecha_creacion_alter_recetas_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='recetas',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
