# Generated by Django 5.2.1 on 2025-08-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_recetas_fecha_modificacion_recetas_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='notas',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
