# Generated by Django 5.2.1 on 2025-08-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_productosfinales_productosintermedios_and_more'),
        ('produccion', '0010_alter_recetas_producto_elaborado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='producto_elaborado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta_producto_elaborado', to='inventario.productoselaborados'),
        ),
    ]
