@hostname = localhost
@port = 8000

@base_url = http://{{hostname}}:{{port}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3MDIwOTc1LCJpYXQiOjE3NTcwMTE1MjAsImp0aSI6IjdkZmRiZGNmZDM4MzRlYTRhMDY0YThjMDU5Y2MzYzJmIiwidXNlcl9pZCI6Mn0.765MjHI7J6JljURyohKrM8Ncc5baVGWeUORstO6FDbk

POST {{base_url}}/productoselaborados/47/get-receta-producto/
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{base_url}}/recetas/15/get_receta_detalles/
Content-Type: application/json
Authorization: Bearer {{token}}