@hostname = localhost
@port = 8000

@base_url = http://{{hostname}}:{{port}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4NjUzMDAyLCJpYXQiOjE3NTg1NzYxNjYsImp0aSI6IjVjOWE4YWQwODc5ZDRiZGE5ZWZkMGZjMWNmODk2NTU3IiwidXNlcl9pZCI6Mn0.OKrgylQjLwuNmxNIq7mqoEoYDpOmoRnEOudTSh6vRo4
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{base_url}}/recetas/15/get_receta_detalles/
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{base_url}}/productosfinales-lista-transformacion/
Content-Type: application/json
Authorization: Bearer {{token}}


###

GET {{base_url}}/produccion-detalles/24
Content-Type: application/json
Authorization: Bearer {{token}}

###