@hostname = localhost
@port = 8000

@base_url = http://{{hostname}}:{{port}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3MDk3OTU1LCJpYXQiOjE3NTcwODk2ODksImp0aSI6IjBkYWJhZjdlYzc0OTRlNTk5NzI3MDBkZTdkMTYzMzk3IiwidXNlcl9pZCI6Mn0.N3vB82Jlgsoa90nn9NvxmeRmrHixs7kYc62z6uwEuTc
GET {{base_url}}/productoselaborados/47/get-receta-producto/
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{base_url}}/recetas/15/get_receta_detalles/
Content-Type: application/json
Authorization: Bearer {{token}}