# Generated by Django 5.2.1 on 2025-09-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0015_alter_productoselaborados_vendible_por_medida_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_transformacion', models.CharField(max_length=255)),
                ('cantidad_origen', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_destino', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjecutarTransformacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_transformacion', models.CharField(max_length=255)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('producto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecutar_transformacion_producto_destino', to='inventario.productoselaborados')),
                ('producto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecutar_transformacion_producto_origen', to='inventario.productoselaborados')),
            ],
        ),
    ]
