# Generated by Django 5.2.1 on 2025-10-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecutartransformacion',
            name='nombre_transformacion',
        ),
        migrations.AddField(
            model_name='ejecutartransformacion',
            name='transformacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='transformacion.transformacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejecutartransformacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
