# Generated by Django 5.2.1 on 2026-01-23 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_productoselaborados_usado_en_transformaciones'),
        ('transformacion', '0002_remove_ejecutartransformacion_nombre_transformacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotesConsumidosTransformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_creada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lote_producto_elaborado_consumido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_consumidos_transformacion', to='inventario.lotesproductoselaborados')),
                ('lote_producto_elaborado_creado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_creados_transformacion', to='inventario.lotesproductoselaborados')),
                ('transformacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_consumidos', to='transformacion.transformacion')),
            ],
        ),
    ]
