# Generated by Django 5.2.1 on 2025-06-26 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_unidadesdemedida_nombre_completo'),
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiasprimas',
            name='cantidad_empaque_estandar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materiasprimas',
            name='nombre_empaque_estandar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materiasprimas',
            name='unidad_medida_empaque_estandar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas_empaque', to='core.unidadesdemedida'),
        ),
    ]
