# Generated by Django 5.2.1 on 2025-06-28 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_initial'),
        ('inventario', '0003_alter_materiasprimas_cantidad_empaque_estandar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotesmateriasprimas',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores'),
        ),
    ]
