# Generated by Django 5.2.1 on 2025-08-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriasproductoselaborados_es_intermediario'),
        ('inventario', '0006_remove_productoselaborados_intermediario_punto_reorden_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productoselaborados',
            name='intermedio_o_producto',
        ),
        migrations.AddConstraint(
            model_name='productoselaborados',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('es_intermediario', True), ('tipo_manejo_venta__isnull', True), ('unidad_venta__isnull', True)), models.Q(('es_intermediario', False), ('tipo_manejo_venta__isnull', False), ('unidad_venta__isnull', False)), _connector='OR'), name='intermedio_o_producto'),
        ),
    ]
