# Generated by Django 5.2.1 on 2025-08-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriasproductoselaborados_es_intermediario'),
        ('inventario', '0007_remove_productoselaborados_intermedio_o_producto_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productoselaborados',
            name='intermedio_o_producto',
        ),
        migrations.AddConstraint(
            model_name='productoselaborados',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('es_intermediario', True), ('precio_venta_usd__isnull', True)), models.Q(('es_intermediario', False), ('precio_venta_usd__isnull', False)), _connector='OR'), name='intermedio_o_producto'),
        ),
    ]
