# Generated by Django 5.2.1 on 2025-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('produccion', '0001_initial'),  # Adjust number if needed
    ]

    operations = [
        migrations.CreateModel(
            name='RecetasDetalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Receta', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='recetas',
            name='receta_detalle',
            field=models.ForeignKey(on_delete=models.CASCADE, to='produccion.recetasdetalles'),
        ),
    ]