# Generated by Django 5.2.1 on 2025-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        # Redundant operations removed to fix SQLite initialization conflict.
    ]