# Generated by Django 5.2.1 on 2025-08-14 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_productosfinales_productosintermedios_and_more'),
        ('produccion', '0008_alter_recetas_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='producto_elaborado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta_producto_elaborado', to='inventario.productoselaborados'),
        ),
        migrations.AlterField(
            model_name='recetasdetalles',
            name='componente_producto_intermedio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta_componente_producto_intermedio', to='inventario.productoselaborados'),
        ),
        migrations.CreateModel(
            name='RelacionesRecetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_principal', to='produccion.recetas')),
                ('subreceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreceta', to='produccion.recetas')),
            ],
        ),
    ]
