# Generated by Django 5.2.1 on 2025-09-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_productosfinales_productosintermedios_and_more'),
        ('produccion', '0011_alter_recetas_producto_elaborado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetasdetalles',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='producto_elaborado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receta_producto_elaborado', to='inventario.productoselaborados'),
        ),
        migrations.AlterUniqueTogether(
            name='recetasdetalles',
            unique_together={('receta', 'componente_materia_prima'), ('receta', 'componente_producto_intermedio')},
        ),
    ]
