# Generated by Django 5.2.1 on 2025-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_recetasdetalles_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='notas',
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
