# Generated by Django 5.2.1 on 2025-09-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_productosfinales_productosintermedios_and_more'),
        ('produccion', '0013_remove_produccion_notas_produccion_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproduccioncosumos',
            name='lote_materia_prima_consumida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lotesmateriasprimas'),
        ),
        migrations.AlterField(
            model_name='detalleproduccioncosumos',
            name='lote_producto_intermedio_consumido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lotesproductoselaborados'),
        ),
        migrations.AlterField(
            model_name='detalleproduccioncosumos',
            name='materia_prima_consumida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas'),
        ),
        migrations.AlterField(
            model_name='detalleproduccioncosumos',
            name='producto_intermedio_consumido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productoselaborados'),
        ),
    ]
