# Generated by Django 5.2.1 on 2025-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_alter_detalleproduccioncosumos_lote_materia_prima_consumida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='fecha_produccion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
