# Generated by Django 5.2.1 on 2025-09-17 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriasproductoselaborados_es_intermediario'),
        ('produccion', '0015_alter_produccion_fecha_produccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproduccioncosumos',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='costo_consumo_usd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produccion',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida'),
        ),
    ]
