# Generated by Django 5.2.1 on 2025-09-21 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_productoselaborados_vendible_por_medida_real'),
        ('produccion', '0016_remove_detalleproduccioncosumos_unidad_medida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProduccionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costo_parcial_usd', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='detalleproduccioncosumos',
            name='materia_prima_or_producto_intermedio_and_lote_required',
        ),
        migrations.RemoveField(
            model_name='detalleproduccioncosumos',
            name='lote_materia_prima_consumida',
        ),
        migrations.RemoveField(
            model_name='detalleproduccioncosumos',
            name='lote_producto_intermedio_consumido',
        ),
        migrations.AddConstraint(
            model_name='detalleproduccioncosumos',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('materia_prima_consumida__isnull', False), ('producto_intermedio_consumido__isnull', True)), models.Q(('materia_prima_consumida__isnull', True), ('producto_intermedio_consumido__isnull', False)), _connector='OR'), name='mp_o_pi_en_detalle'),
        ),
        migrations.AddField(
            model_name='detalleproduccionlote',
            name='detalle_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='produccion.detalleproduccioncosumos'),
        ),
        migrations.AddField(
            model_name='detalleproduccionlote',
            name='lote_materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lotesmateriasprimas'),
        ),
        migrations.AddField(
            model_name='detalleproduccionlote',
            name='lote_producto_intermedio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lotesproductoselaborados'),
        ),
        migrations.AddConstraint(
            model_name='detalleproduccionlote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lote_materia_prima__isnull', False), ('lote_producto_intermedio__isnull', True)), models.Q(('lote_materia_prima__isnull', True), ('lote_producto_intermedio__isnull', False)), _connector='OR'), name='un_solo_tipo_lote_en_detalle'),
        ),
    ]
