# Generated by Django 5.2.1 on 2026-01-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0017_detalleproduccionlote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cantidad de producto que genera esta receta', max_digits=10, null=True),
        ),
    ]
