# Generated by Django 5.2.1 on 2025-06-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenesCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_linea_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenesCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision_oc', models.DateField()),
                ('fecha_entrega_esperada', models.DateField()),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('subtotal_oc_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_impuestos_oc_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total_oc_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_oc_ves', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_impuestos_oc_ves', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total_oc_ves', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccion_envio', models.TextField(blank=True, max_length=255, null=True)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('apellido_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=100, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion_registro', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
