# Generated by Django 5.2.1 on 2025-06-23 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordenescompra',
            name='materia_prima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas'),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='producto_reventa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productosreventa'),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='unidad_medida_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='ordenescompra',
            name='estado_oc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estadosordencompra'),
        ),
        migrations.AddField(
            model_name='ordenescompra',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metodosdepago'),
        ),
    ]
