# Generated by Django 5.2.1 on 2025-06-23 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenescompra',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordenescompra'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenescompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores'),
        ),
        migrations.AddConstraint(
            model_name='detalleordenescompra',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('materia_prima__isnull', False), ('producto_reventa__isnull', True)), models.Q(('materia_prima__isnull', True), ('producto_reventa__isnull', False)), _connector='OR'), name='detalle_orden_compra_un_solo_tipo_de_producto'),
        ),
    ]
