# Generated by Django 5.2.1 on 2025-08-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotesProductosElaborados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial_lote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual_lote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_produccion', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('coste_unitario_lote_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=False)),
                ('peso_nominal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotesProductosReventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual_lote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coste_unitario_lote_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriasPrimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SKU', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre_empaque_estandar', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_empaque_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('punto_reorden', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ultima_actualizacion', models.DateField(auto_now=True)),
                ('fecha_creacion_registro', models.DateField(auto_now_add=True)),
                ('fecha_modificacion_registro', models.DateField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosElaborados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, unique=True)),
                ('SKU', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('tipo_manejo_venta', models.CharField(choices=[('UNIDAD', 'Unidad'), ('PESO_VOLUMEN', 'Peso_Volumen')], max_length=15)),
                ('precio_venta_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('punto_reorden', models.IntegerField(default=0)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion_registro', models.DateField(auto_now_add=True)),
                ('es_intermediario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosReventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('SKU', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_manejo_venta', models.CharField(choices=[('UNIDAD', 'Unidad'), ('PESO_VOLUMEN', 'Peso_Volumen')], max_length=15)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_ultima_compra_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pecedero', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_creacion_registro', models.DateField(auto_now_add=True)),
                ('fecha_modificacion_registro', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotesMateriasPrimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual_lote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=False)),
                ('detalle_oc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.detalleordenescompra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores')),
            ],
        ),
    ]
