# Generated by Django 5.2.1 on 2025-08-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesproductoselaborados',
            name='produccion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.produccion'),
        ),
        migrations.AddField(
            model_name='lotesproductosreventa',
            name='detalle_oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.detalleordenescompra'),
        ),
        migrations.AddField(
            model_name='lotesproductosreventa',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores'),
        ),
        migrations.AddField(
            model_name='materiasprimas',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriasmateriaprima'),
        ),
        migrations.AddField(
            model_name='materiasprimas',
            name='unidad_medida_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas_unidad_base', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='materiasprimas',
            name='unidad_medida_empaque_estandar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas_empaque', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='lotesmateriasprimas',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas'),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriasproductoselaborados'),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='unidad_medida_nominal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_elaborados_unidad_nominal', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='unidad_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_elaborados_unidad_venta', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='lotesproductoselaborados',
            name='producto_elaborado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productoselaborados'),
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriasproductosreventa'),
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='proveedor_preferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores'),
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='unidad_base_inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='lotesproductosreventa',
            name='producto_reventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productosreventa'),
        ),
        migrations.AddConstraint(
            model_name='productoselaborados',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('es_intermediario', True), ('precio_venta_usd__isnull', False)), models.Q(('es_intermediario', False), ('precio_venta_usd__isnull', True)), _connector='OR'), name='intermediario_punto_reorden'),
        ),
    ]
