# Generated by Django 5.2.1 on 2025-08-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoselaborados',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
