# Generated by Django 5.2.1 on 2025-08-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_productoselaborados_punto_reorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoselaborados',
            name='tipo_manejo_venta',
            field=models.CharField(blank=True, choices=[('UNIDAD', 'Unidad'), ('PESO_VOLUMEN', 'Peso_Volumen')], max_length=15, null=True),
        ),
    ]
