# Generated by Django 5.2.1 on 2025-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriasproductoselaborados_es_intermediario'),
        ('inventario', '0004_alter_productoselaborados_tipo_manejo_venta'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productoselaborados',
            name='intermediario_punto_reorden',
        ),
        migrations.AlterField(
            model_name='productoselaborados',
            name='precio_venta_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='productoselaborados',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('es_intermediario', True), ('tipo_manejo_venta__isnull', True), ('precio_venta_usd__isnull', True), ('unidad_venta__isnull', True)), models.Q(('es_intermediario', False), ('tipo_manejo_venta__isnull', False), ('precio_venta_usd__isnull', False), ('unidad_venta__isnull', False)), _connector='OR'), name='intermediario_punto_reorden'),
        ),
    ]
