# Generated by Django 5.2.1 on 2025-08-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_productoselaborados_intermedio_o_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosFinales',
            fields=[
            ],
            options={
                'verbose_name': 'Producto Final',
                'verbose_name_plural': 'Productos Finales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.productoselaborados',),
        ),
        migrations.CreateModel(
            name='ProductosIntermedios',
            fields=[
            ],
            options={
                'verbose_name': 'Producto Intermedio',
                'verbose_name_plural': 'Productos Intermedios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.productoselaborados',),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='fecha_modificacion_registro',
            field=models.DateField(auto_now=True),
        ),
    ]
