# Generated by Django 5.2.1 on 2025-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_productosfinales_productosintermedios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesmateriasprimas',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible para uso'), ('EXPIRADO', 'Expirado'), ('AGOTADO', 'Agotado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='lotesmateriasprimas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
