# Generated by Django 5.2.1 on 2025-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_lotesmateriasprimas_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotesproductoselaborados',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='lotesproductoselaborados',
            name='notas',
        ),
        migrations.AddField(
            model_name='lotesproductoselaborados',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible para uso'), ('EXPIRADO', 'Expirado'), ('AGOTADO', 'Agotado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='lotesproductoselaborados',
            name='fecha_produccion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
