# Generated by Django 5.2.1 on 2025-09-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriasproductoselaborados_es_intermediario'),
        ('inventario', '0012_remove_lotesproductoselaborados_activo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productoselaborados',
            name='intermedio_o_producto',
        ),
        migrations.RenameField(
            model_name='lotesproductoselaborados',
            old_name='coste_unitario_lote_usd',
            new_name='coste_total_lote_usd',
        ),
        migrations.RemoveField(
            model_name='lotesproductoselaborados',
            name='peso_nominal',
        ),
        migrations.RemoveField(
            model_name='productoselaborados',
            name='tipo_manejo_venta',
        ),
        migrations.RemoveField(
            model_name='productoselaborados',
            name='unidad_medida_nominal',
        ),
        migrations.AddField(
            model_name='lotesproductoselaborados',
            name='peso_total_lote_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual measured weight of entire batch in grams', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lotesproductoselaborados',
            name='volumen_total_lote_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual measured volume of entire batch in milliliters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='tipo_medida_fisica',
            field=models.CharField(choices=[('UNIDAD', 'Unidad'), ('PESO', 'Peso'), ('VOLUMEN', 'Volumen')], default='PESO', max_length=10),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='unidad_produccion',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se produce y se gestiona el stock (e.g., Unidades, Gramos).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_elaborados_unidad_produccion', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='vendible_por_medida_real',
            field=models.BooleanField(default=False, help_text='Si es True, el precio final se calcula midiendo peso/volumen en la venta.'),
        ),
        migrations.AlterField(
            model_name='productoselaborados',
            name='unidad_venta',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se vende el producto (e.g., Unidades, Kilogramos, Litros).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_elaborados_unidad_venta', to='core.unidadesdemedida'),
        ),
        migrations.AddConstraint(
            model_name='productoselaborados',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('es_intermediario', True), ('precio_venta_usd__isnull', True), ('unidad_venta__isnull', True), ('vendible_por_medida_real__isnull', True)), models.Q(('es_intermediario', False), ('precio_venta_usd__isnull', False), ('unidad_venta__isnull', False), ('vendible_por_medida_real__isnull', False)), _connector='OR'), name='intermedio_o_producto'),
        ),
    ]
