# Generated by Django 5.2.1 on 2025-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_remove_productoselaborados_intermedio_o_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoselaborados',
            name='vendible_por_medida_real',
            field=models.BooleanField(blank=True, default=False, help_text='Si es True, el precio final se calcula midiendo peso/volumen en la venta.', null=True),
        ),
    ]
