# Generated by Django 5.2.1 on 2025-10-05 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriasproductoselaborados_es_intermediario'),
        ('inventario', '0015_alter_productoselaborados_vendible_por_medida_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotesproductosreventa',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='productosreventa',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='productosreventa',
            name='tipo_manejo_venta',
        ),
        migrations.AddField(
            model_name='lotesproductosreventa',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible para uso'), ('EXPIRADO', 'Expirado'), ('AGOTADO', 'Agotado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=10),
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Cuántas unidades de inventario equivalen a 1 unidad de venta', max_digits=10),
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='unidad_venta',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se vende el producto (ej: Unidad para bolsa de 1kg)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_reventa_venta', to='core.unidadesdemedida'),
        ),
        migrations.AlterField(
            model_name='productosreventa',
            name='precio_venta_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio por unidad de venta', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productosreventa',
            name='unidad_base_inventario',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se gestiona el stock (ej: Unidad para latas, Gramos para jamón)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_reventa_inventario', to='core.unidadesdemedida'),
        ),
    ]
