# Generated by Django 5.2.1 on 2025-10-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_remove_lotesproductosreventa_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotesproductosreventa',
            name='notas',
        ),
    ]
