# Generated by Django 5.2.1 on 2025-11-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_remove_lotesproductosreventa_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosreventa',
            name='costo_ultima_compra_usd',
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='precio_compra_usd',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
