# Generated by Django 5.2.1 on 2025-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_remove_productosreventa_costo_ultima_compra_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiasprimas',
            name='precio_compra',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
