# Generated by Django 5.2.1 on 2025-11-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_remove_materiasprimas_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiasprimas',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
