# Generated by Django 5.2.1 on 2025-11-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_materiasprimas_precio_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiasprimas',
            name='precio_compra',
        ),
    ]
