# Generated by Django 5.2.1 on 2025-11-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_materiasprimas_precio_compra_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiasprimas',
            name='precio_compra_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productosreventa',
            name='precio_compra_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
