# Generated by Django 5.2.1 on 2025-11-25 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_unit_conversions'),
        ('inventario', '0024_alter_materiasprimas_precio_compra_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosreventa',
            name='punto_reorden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productoselaborados',
            name='unidad_produccion',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se produce y se gestiona el stock (e.g., Unidades, uGramos).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_elaborados_unidad_produccion', to='core.unidadesdemedida'),
        ),
    ]
