# Generated by Django 5.2.1 on 2025-12-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_productosreventa_punto_reorden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosreventa',
            old_name='pecedero',
            new_name='perecedero',
        ),
    ]
