# Generated by Django 5.2.1 on 2026-01-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_rename_pecedero_productosreventa_perecedero'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoselaborados',
            name='usado_en_transformaciones',
            field=models.BooleanField(default=False),
        ),
    ]
