# Generated by Django 5.2.1 on 2025-10-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesordenventa',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='detallesordenventa',
            name='produccion_asociada',
        ),
        migrations.AddField(
            model_name='detallesordenventa',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallesordenventa',
            name='impuesto_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='estado_orden',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=100),
        ),
    ]
