# Generated by Django 5.2.1 on 2025-10-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nombre_estado_oc_estadosordencompra_nombre_estado_and_more'),
        ('ventas', '0002_remove_detallesordenventa_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='estado_orden_new',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.estadosordenventa'
            ),
        ),
    ]

