# Generated by Django 5.2.1 on 2025-10-12 00:01

from django.db import migrations


def migrate_estado_orden(apps, schema_editor):
    """
    Convert CharField estado_orden values to ForeignKey references.
    """
    OrdenVenta = apps.get_model('ventas', 'OrdenVenta')
    EstadosOrdenVenta = apps.get_model('core', 'EstadosOrdenVenta')
    
    db_alias = schema_editor.connection.alias
    
    # Create estado records if they don't exist
    estado_mapping = {
        'Pendiente': 'Orden pendiente de confirmación',
        'En Proceso': 'Orden en proceso de preparación',
        'Completado': 'Orden completada y entregada',
        'Cancelado': 'Orden cancelada',
    }
    
    estados_created = {}
    for nombre, descripcion in estado_mapping.items():
        estado, created = EstadosOrdenVenta.objects.using(db_alias).get_or_create(
            nombre_estado=nombre,
            defaults={'descripcion': descripcion}
        )
        estados_created[nombre] = estado
    
    # Migrate existing OrdenVenta records
    for orden in OrdenVenta.objects.using(db_alias).all():
        if hasattr(orden, 'estado_orden') and orden.estado_orden:
            # Map the old CharField value to the new ForeignKey
            estado_text = orden.estado_orden
            if estado_text in estados_created:
                orden.estado_orden_new = estados_created[estado_text]
                orden.save(using=db_alias, update_fields=['estado_orden_new'])


def reverse_migrate_estado_orden(apps, schema_editor):
    """
    Reverse migration - convert ForeignKey back to CharField values.
    """
    OrdenVenta = apps.get_model('ventas', 'OrdenVenta')
    db_alias = schema_editor.connection.alias
    
    for orden in OrdenVenta.objects.using(db_alias).all():
        if orden.estado_orden_new:
            orden.estado_orden = orden.estado_orden_new.nombre_estado
            orden.save(using=db_alias, update_fields=['estado_orden'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nombre_estado_oc_estadosordencompra_nombre_estado_and_more'),
        ('ventas', '0003_ordenventa_estado_orden_new'),
    ]

    operations = [
        migrations.RunPython(migrate_estado_orden, reverse_migrate_estado_orden),
    ]

