# Generated by Django 5.2.1 on 2025-10-12 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nombre_estado_oc_estadosordencompra_nombre_estado_and_more'),
        ('ventas', '0004_migrate_estado_orden_data'),
    ]

    operations = [
        # Remove the old CharField
        migrations.RemoveField(
            model_name='ordenventa',
            name='estado_orden',
        ),
        # Rename the new ForeignKey field to the original name
        migrations.RenameField(
            model_name='ordenventa',
            old_name='estado_orden_new',
            new_name='estado_orden',
        ),
        # Make it non-nullable now that all data is migrated
        migrations.AlterField(
            model_name='ordenventa',
            name='estado_orden',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.estadosordenventa'
            ),
        ),
    ]

