# Generated by Django 5.2.1 on 2025-10-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_complete_estado_orden_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesordenventa',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallesordenventa',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallesordenventa',
            name='impuesto_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallesordenventa',
            name='precio_unitario_usd',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallesordenventa',
            name='subtotal_linea_usd',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='monto_descuento_usd',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='monto_total_usd',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='monto_total_ves',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='tasa_cambio_aplicada',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
