# Generated by Django 5.2.1 on 2025-10-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_detallesordenventa_cantidad_solicitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='monto_impuestos_usd',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
