# Generated by Django 5.2.1 on 2025-10-17 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nombre_estado_oc_estadosordencompra_nombre_estado_and_more'),
        ('ventas', '0007_ordenventa_monto_impuestos_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.metodosdepago'),
        ),
    ]
