# Generated by Django 5.2.1 on 2025-10-17 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_ordenventa_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesordenventa',
            name='orden_venta_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ventas.ordenventa'),
        ),
    ]
