# Generated by Django 5.2.1 on 2025-10-21 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_remove_lotesproductosreventa_notas'),
        ('ventas', '0009_alter_detallesordenventa_orden_venta_asociada'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenConsumoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle_orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.detallesordenventa')),
                ('orden_venta_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='ventas.ordenventa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenConsumoLoteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costo_parcial_usd', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('lote_producto_elaborado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductoselaborados')),
                ('lote_producto_reventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductosreventa')),
                ('orden_consumo_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_lotes', to='ventas.ordenconsumolote')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('lote_producto_elaborado__isnull', False), ('lote_producto_reventa__isnull', True)), models.Q(('lote_producto_elaborado__isnull', True), ('lote_producto_reventa__isnull', False)), _connector='OR'), name='detalle_orden_consumo_lote_un_solo_tipo_de_producto')],
            },
        ),
    ]
