# Generated by Django 5.2.1 on 2025-10-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_ordenconsumolote_ordenconsumolotedetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='fecha_entrega_definitiva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
