# Generated by Django 5.2.1 on 2025-12-15 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_ordenventa_fecha_entrega_definitiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.clientes'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='usuario_cajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AperturaCierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_inicial_ves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_final_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_final_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas_apertura', models.TextField(blank=True, null=True)),
                ('notas_cierre', models.TextField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apertura/Cierre de Caja',
                'verbose_name_plural': 'Aperturas/Cierres de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='ventas',
            name='apertura_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.aperturacierrecaja'),
        ),
        migrations.AddConstraint(
            model_name='aperturacierrecaja',
            constraint=models.UniqueConstraint(condition=models.Q(('esta_activa', True)), fields=('esta_activa',), name='solo_una_caja_activa'),
        ),
    ]
