# Generated by Django 5.2.1 on 2025-12-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_ventas_cliente_alter_ventas_usuario_cajero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario_ves',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='subtotal_linea_ves',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagos',
            name='cambio_efectivo_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='cambio_efectivo_ves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal_linea_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
