# Generated by Django 5.2.1 on 2025-12-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_detalleventa_precio_unitario_ves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_cambio_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_cambio_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_efectivo_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_efectivo_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_pago_movil_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_pago_movil_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_tarjeta_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_tarjeta_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_transferencia_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_transferencia_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aperturacierrecaja',
            name='total_ventas_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aperturacierrecaja',
            name='total_ventas_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
