# Generated by Django 5.2.1 on 2025-12-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_aperturacierrecaja_total_cambio_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturacierrecaja',
            name='diferencia_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aperturacierrecaja',
            name='diferencia_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
