# Generated by Django 5.2.1 on 2025-12-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_rename_pecedero_productosreventa_perecedero'),
        ('ventas', '0015_alter_aperturacierrecaja_diferencia_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasLotesVendidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='detalleventa',
            name='producto_elaborado_requiere_lote',
        ),
        migrations.RemoveConstraint(
            model_name='detalleventa',
            name='lote_elaborado_solo_con_producto_elaborado',
        ),
        migrations.RemoveConstraint(
            model_name='detalleventa',
            name='lote_reventa_solo_con_producto_reventa',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='lote_producto_elaborado_vendido',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='lote_producto_reventa_vendido',
        ),
        migrations.AlterField(
            model_name='ordenconsumolote',
            name='orden_venta_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_lotes_orden_venta', to='ventas.ordenventa'),
        ),
        migrations.AddField(
            model_name='ventaslotesvendidos',
            name='detalle_venta_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_vendidos', to='ventas.detalleventa'),
        ),
        migrations.AddField(
            model_name='ventaslotesvendidos',
            name='lote_producto_elaborado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductoselaborados'),
        ),
        migrations.AddField(
            model_name='ventaslotesvendidos',
            name='lote_producto_reventa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductosreventa'),
        ),
        migrations.AddConstraint(
            model_name='ventaslotesvendidos',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lote_producto_elaborado__isnull', False), ('lote_producto_reventa__isnull', True)), models.Q(('lote_producto_elaborado__isnull', True), ('lote_producto_reventa__isnull', False)), _connector='OR'), name='venta_lotes_vendidos_un_solo_tipo'),
        ),
    ]
