# Generated by Django 5.2.1 on 2025-12-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_ventaslotesvendidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_cambio_efectivo_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_cambio_efectivo_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_cambio_pago_movil_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='total_cambio_pago_movil_ves',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='cambio_pago_movil_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='cambio_pago_movil_ves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
