# Generated by Django 5.2.1 on 2025-08-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriasproductoselaborados',
            name='es_intermediario',
            field=models.BooleanField(default=False),
        ),
    ]
