# Generated by Django 5.2.1 on 2025-10-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenescompra',
            name='email_enviado',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenescompra',
            name='fecha_envio_oc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenescompra',
            name='terminos_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
