# Generated by Django 5.2.1 on 2025-10-27 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_ordenescompra_email_enviado_and_more'),
        ('core', '0003_rename_nombre_estado_oc_estadosordencompra_nombre_estado_and_more'),
        ('inventario', '0017_remove_lotesproductosreventa_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False, help_text='Indica si esta recepción ha sido pagada completamente')),
                ('monto_pendiente_pago_usd', models.DecimalField(decimal_places=2, default=0, help_text='Monto pendiente de pago en USD', max_digits=10)),
                ('fecha_recepcion', models.DateField(help_text='Fecha en que se recibió la mercancía')),
                ('numero_factura_proveedor', models.CharField(blank=True, help_text='Número de factura del proveedor para esta entrega', max_length=100, null=True)),
                ('numero_remision', models.CharField(blank=True, help_text='Número de guía de remisión o nota de entrega', max_length=100, null=True)),
                ('monto_recepcion_usd', models.DecimalField(decimal_places=2, default=0, help_text='Monto total de esta recepción en USD', max_digits=10)),
                ('monto_recepcion_ves', models.DecimalField(decimal_places=2, default=0, help_text='Monto total de esta recepción en VES', max_digits=10)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=2, default=0, help_text='Tasa de cambio USD/VES al momento de la recepción', max_digits=10)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre la recepción', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden_compra', models.ForeignKey(help_text='Orden de compra asociada a esta recepción', on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='compras.ordenescompra')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que realizó la entrega', on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores')),
                ('usuario_recepcionador', models.ForeignKey(help_text='Usuario que registró la recepción de mercancía', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra/Recepción',
                'verbose_name_plural': 'Compras/Recepciones',
                'ordering': ['-fecha_recepcion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagosProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago')),
                ('monto_pago_usd', models.DecimalField(decimal_places=2, help_text='Monto pagado en USD', max_digits=10)),
                ('monto_pago_ves', models.DecimalField(decimal_places=2, help_text='Monto pagado en VES', max_digits=10)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=2, help_text='Tasa de cambio USD/VES al momento del pago', max_digits=10)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de referencia de transferencia/transacción', max_length=100, null=True)),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número de comprobante de pago', max_length=100, null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el pago', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compra_asociada', models.ForeignKey(blank=True, help_text='Compra/recepción específica a la que se aplica este pago', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.compras')),
                ('metodo_pago', models.ForeignKey(help_text='Método utilizado para el pago', on_delete=django.db.models.deletion.CASCADE, to='core.metodosdepago')),
                ('orden_compra_asociada', models.ForeignKey(blank=True, help_text='Orden de compra a la que se aplica este pago', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.ordenescompra')),
                ('proveedor', models.ForeignKey(help_text='Proveedor al que se realiza el pago', on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores')),
                ('usuario_registrador', models.ForeignKey(help_text='Usuario que registró el pago', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, help_text='Cantidad recibida en esta entrega', max_digits=10)),
                ('costo_unitario_usd', models.DecimalField(decimal_places=2, help_text='Costo unitario en USD', max_digits=10)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, help_text='Subtotal de esta línea (cantidad * costo_unitario)', max_digits=10)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre este producto recibido', max_length=255, null=True)),
                ('compra', models.ForeignKey(help_text='Compra/recepción a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compras')),
                ('detalle_oc', models.ForeignKey(help_text='Línea de la OC correspondiente a este producto', on_delete=django.db.models.deletion.CASCADE, to='compras.detalleordenescompra')),
                ('materia_prima', models.ForeignKey(blank=True, help_text='Materia prima recibida', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas')),
                ('producto_reventa', models.ForeignKey(blank=True, help_text='Producto de reventa recibido', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productosreventa')),
                ('unidad_medida', models.ForeignKey(help_text='Unidad de medida de la cantidad recibida', on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('materia_prima__isnull', False), ('producto_reventa__isnull', True)), models.Q(('materia_prima__isnull', True), ('producto_reventa__isnull', False)), _connector='OR'), name='detalle_compra_un_solo_tipo_de_producto')],
            },
        ),
    ]
