# Generated by Django 5.2.1 on 2025-10-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_compras_pagosproveedores_detallecompras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleordenescompra',
            name='notas',
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='impuesto_linea_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
