# Generated by Django 5.2.1 on 2025-10-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_remove_detalleordenescompra_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenescompra',
            name='monto_impuestos_oc_usd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='monto_impuestos_oc_ves',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='monto_total_oc_usd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='monto_total_oc_ves',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='subtotal_oc_usd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='subtotal_oc_ves',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='tasa_cambio_aplicada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
