# Generated by Django 5.2.1 on 2025-11-01 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_ordenescompra_monto_impuestos_oc_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordenescompra'),
        ),
    ]
