# Generated by Django 5.2.1 on 2025-11-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_detalleordenescompra_orden_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleordenescompra',
            name='impuesto_linea_usd',
        ),
        migrations.RemoveField(
            model_name='detalleordenescompra',
            name='porcentaje_impuesto',
        ),
        migrations.RemoveField(
            model_name='ordenescompra',
            name='monto_impuestos_oc_usd',
        ),
        migrations.RemoveField(
            model_name='ordenescompra',
            name='monto_impuestos_oc_ves',
        ),
    ]
