# Generated by Django 5.2.1 on 2025-11-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_remove_detalleordenescompra_impuesto_linea_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenescompra',
            name='subtotal_oc_usd',
        ),
        migrations.RemoveField(
            model_name='ordenescompra',
            name='subtotal_oc_ves',
        ),
    ]
