# Generated by Django 5.2.1 on 2025-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_remove_ordenescompra_subtotal_oc_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosproveedores',
            name='tasa_cambio_aplicada',
            field=models.DecimalField(decimal_places=3, help_text='Tasa de cambio USD/VES al momento del pago', max_digits=10),
        ),
    ]
