# Generated by Django 5.2.1 on 2025-11-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_alter_pagosproveedores_tasa_cambio_aplicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosproveedores',
            name='monto_pago_usd',
            field=models.DecimalField(decimal_places=3, help_text='Monto pagado en USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagosproveedores',
            name='monto_pago_ves',
            field=models.DecimalField(decimal_places=3, help_text='Monto pagado en VES', max_digits=10),
        ),
    ]
