# Generated by Django 5.2.1 on 2025-11-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_alter_pagosproveedores_monto_pago_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenescompra',
            name='fecha_email_enviado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
