# Generated by Django 5.2.1 on 2026-01-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_ordenescompra_fecha_email_enviado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='costo_unitario_usd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='subtotal_linea_usd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='monto_total_oc_usd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='monto_total_oc_ves',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='tasa_cambio_aplicada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
