# Generated by Django 5.2.1 on 2026-01-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_alter_detalleordenescompra_cantidad_recibida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='monto_pendiente_pago_usd',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Monto pendiente de pago en USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='compras',
            name='monto_recepcion_usd',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Monto total de esta recepción en USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='compras',
            name='monto_recepcion_ves',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Monto total de esta recepción en VES', max_digits=15),
        ),
        migrations.AlterField(
            model_name='compras',
            name='tasa_cambio_aplicada',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Tasa de cambio USD/VES al momento de la recepción', max_digits=15),
        ),
    ]
