# Generated by Django 5.2.1 on 2025-08-05 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0002_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('rif_cedula', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_orden', models.DateField()),
                ('fecha_entrega_solicitada', models.DateField()),
                ('fecha_entrega_definitiva', models.DateField()),
                ('notas_generales', models.TextField(blank=True, max_length=255, null=True)),
                ('monto_descuento_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('monto_total_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total_ves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('monto_total_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total_ves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
                ('usuario_cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_linea_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
                ('produccion_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.produccion')),
                ('producto_elaborado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productoselaborados')),
                ('producto_reventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productosreventa')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida')),
                ('orden_venta_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ordenventa')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('producto_elaborado__isnull', False), ('producto_reventa__isnull', True)), models.Q(('producto_elaborado__isnull', True), ('producto_reventa__isnull', False)), _connector='OR'), name='detalle_orden_venta_un_solo_tipo_de_producto')],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pago_ves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metodosdepago')),
                ('orden_venta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ordenventa')),
                ('usuario_registrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('venta_asociada__isnull', False), ('orden_venta_asociada__isnull', True)), models.Q(('venta_asociada__isnull', True), ('orden_venta_asociada__isnull', False)), _connector='OR'), name='un_solo_tipo_de_venta_por_pago')],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_linea_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('lote_producto_elaborado_vendido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductoselaborados')),
                ('lote_producto_reventa_vendido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductosreventa')),
                ('producto_elaborado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.productoselaborados')),
                ('producto_reventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.productosreventa')),
                ('unidad_medida_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidadesdemedida')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('producto_elaborado__isnull', False), ('producto_reventa__isnull', True)), models.Q(('producto_elaborado__isnull', True), ('producto_reventa__isnull', False)), _connector='OR'), name='detalle_venta_un_solo_tipo_de_producto'), models.CheckConstraint(condition=models.Q(('producto_elaborado__isnull', True), ('lote_producto_elaborado_vendido__isnull', False), _connector='OR'), name='producto_elaborado_requiere_lote'), models.CheckConstraint(condition=models.Q(('producto_elaborado__isnull', False), ('lote_producto_elaborado_vendido__isnull', True), _connector='OR'), name='lote_elaborado_solo_con_producto_elaborado'), models.CheckConstraint(condition=models.Q(('producto_reventa__isnull', False), ('lote_producto_reventa_vendido__isnull', True), _connector='OR'), name='lote_reventa_solo_con_producto_reventa')],
            },
        ),
    ]
